config/routes.rb
Sqzdin::Application.routes.draw do

  match '/static/about/?'    => 'static#about',   :as => :about
  match '/static/privacy/?'  => 'static#privacy', :as => :privacy
  match '/static/tos/?'      => 'static#tos',     :as => :tos

  match '/api/latest_urls' => 'api#latest_urls',  :as => :latest_urls
  match '/api/create'      => 'api#create',  :via => :post, :as => :create
  match '/api/update/:id'  => 'api#update',  :via => :post, :as => :update
  match '/api/delete/:id'  => 'api#delete',  :via => :post, :as => :delete
  
  match '/admin'           => 'admin#index'
  
  match '/:path_plus'   => 'api#show',   :via => :get, :requirements => {:path_plus => /\+$/}
  match '/:path'   => 'api#expand', :via => :get
  match '/'        => 'api#index',  :via => :get

  root :to => "api#index"

end

app/models/stat.rb
class Stat < ActiveRecord::Base

end

app/models/url.rb
class Url < ActiveRecord::Base
  has_many :stats
  
  IPv4_PART = /\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5]/  # 0-255
  URL_REGEXP = %r{
    \A
    https?://                                        # http:// or https://
    ([^\s:@]+:[^\s:@]*@)?                            # optional username:pw@
    ( (xn--)?[^\W_]+([-.][^\W_]+)*\.[a-z]{2,6}\.? |  # domain (including Punycode/IDN)...
        #{IPv4_PART}(\.#{IPv4_PART}){3} )            # or IPv4
    (:\d{1,5})?                                      # optional port
    ([/?]\S*)?                                       # optional /whatever or ?whatever
    \Z
  }iux


  validates :original_url, 
            :presence => true, 
            :uniqueness => { :case_sensitive => false, :message => "This URL is already in our database" },
            :length => { :maximum => 2024 },
            :format => { :with => URL_REGEXP, :message => "Invalid URL" }
            

  validates :path, 
            :allow_blank => true, 
            :uniqueness => { :case_sensitive => false, :message => "Custom path has already been taken" }, 
            :length => { :maximum => 20, :minimum => 2, :message => "Custom path must be between 2 and 20 characters"},
            :format => { :with => /^[-_a-z0-9]+$/i, :message => "Invalid Path" }


  def self.random_path
    Anybase::Base62.random(path_size).downcase
  end
  
  def self.path_size
    Url.count.to_s.length.to_i-1
  end

  def self.delete!
    self.destroy
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end

end

app/controllers/api_controller.rb
class ApiController < ApplicationController

  PATH_EXCLUSIONS = ['static','api','index','latest_urls','clark','admin','create','update','delete','destroy']
  URL_EXCLUSIONS = []

  def index

    logger.info("\n\n\n params: "+params.inspect+"\n\n\n")
    redirect_to :action => :show   if (params[:path] && params[:path].include?('+'))
    redirect_to :action => :expand if params[:path] and return

    @meta_title = 'Index'
    @body_class = 'index_wrap'
  end

  def create
    404 unless request.post?

    json = {:result => nil}

    url  = params["opts"]["url"]

    begin
      parsed_url = URI.parse(url)
    rescue URI::InvalidURIError => err
      json[:errors] = {"original_url" => "URL is invalid: #{err}"}
    end

    if parsed_url.scheme && parsed_url.host
      path = params["opts"]["path"] 
      path = Url.random_path if path.blank?
      
      unless PATH_EXCLUSIONS.include?(path)
        json[:url] = url
        json[:path] = path
        
        @url = Url.new(:original_url => url, :path => path)

        begin
          json[:result] = @url.save! 
        rescue ActiveRecord::RecordInvalid => invalid
          json[:errors] = invalid.record.errors
          json[:result] = "errors"
        end
      else
        json[:errors] = {"path" => "This custom path is reserved, please try another"}
        json[:result] = "errors"
      end
    else
      json[:errors] = {"original_url" => "This URL is invalid"}
      json[:result] = "errors"
    end
    render :json => json
  end

  def expand
    404 unless params[:path]

    url = Url.find_by_path(params[:path])
    Url.increment_counter(:hits, url.id)
    url.save

    stat = update_stats(url)

    redirect_to url["original_url"] and return
  end

  def show
    @body_class = 'show_wrap'
    path = params["path_plus"].gsub!(/\+/,'')
    url = Url.find_by_path(path)
    render :show, :locals => { :url => url, :stats => url.stats.all }
  end

  def update
    404 unless request.post? && params["record"]

  end

  def delete
    404 unless request.post? && params["record"]
  end

  def latest_urls
    limit = (params[:limit]) ? params[:limit] : 10
    urls = []

    Url.find(:all, :limit => limit, :order => 'created_at desc').each do |url|
      urls << {:id=> url.id,:hits=>url.hits,:original_url=>url.original_url,:path=>url.path,:created_at=>url.created_at}
    end

    respond_to do |format|
      format.json { render :json => urls } 
      format.html { render :partial => "latest_urls", :locals => {:latest_urls => urls} }
    end
    
  end

  def update_stats(url={})
    entry = Stat.new do |s|
      s.url_id       = url.id
      s.referrer     = request.env["HTTP_REFERER"]
      s.user_agent   = request.env["HTTP_USER_AGENT"]
      s.country_code = country_code(url.ip)
      s.ip_address   = request.env["REMOTE_ADDR"]
    end
    entry.save
    return true
  end

  def country_code(ip)
    require "net/http"
    require "uri"
    uri = URI.parse("http://api.hostip.info/country.php?ip=#{ip}")
    response = Net::HTTP.get_response(uri)
    cc = response.body.to_s
    cc
  end

  protected

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def tos
  end

  def privacy
  end

  def about
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/admin/index.html.erb
<h1>sqzd.in</h1>
<h3>Administration</h3>

app/views/layouts/_footer.html.erb
<ul class="individual plastic">
  <li><%= link_to "Terms of Service", tos_path -%></li>  
  <li><%= link_to "Privacy", privacy_path -%></li>  
  <li><%= link_to "About", about_path -%></li>  
</ul>

app/views/layouts/_header.html.erb
<%= link_to("back","/",:class=>"back") if request.path.include?('+') -%>

<%= link_to('<span class="logo">sqzd.in</span>'.html_safe,"/") -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6 lte7 lte8 lte9"><![endif]-->
<!--[if IE 7 ]><html class="ie ie7 lte7 lte8 lte9"><![endif]-->
<!--[if IE 8 ]><html class="ie ie8 lte8 lte9"><![endif]-->
<!--[if IE 9 ]><html class="ie ie9 lte9"><![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--><html class=""><!--<![endif]-->
<head>
  <meta charset="UTF-8" />
  <title><%= @meta_title -%></title>
  <%= stylesheet_link_tag 'screen.css', :media => 'screen, projection' %>
  <%= stylesheet_link_tag 'base.css',   :media => 'screen, projection' %>
  <%= stylesheet_link_tag 'print.css',  :media => 'print' %>


  <%= javascript_include_tag :defaults %>

  <%= javascript_include_tag 'jqtouch.js', :type => 'application/x-javascript', :charset => 'utf-8' %>
  <%= stylesheet_link_tag 'jqtouch.css', :media => 'screen, projection' %>
  <%= stylesheet_link_tag 'themes/jqt/theme.css', :media => 'screen, projection' %>

  <%= stylesheet_link_tag 'jquery.qtip.css',   :media => 'screen, projection' %>
  <%= javascript_include_tag 'jquery.qtip.min' %>

  <%= csrf_meta_tag %>

  <meta http-equiv="imagetoolbar" content="false" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <meta name="viewport" content="user-scalable=no, width=device-width" /> 
</head>
<body class="<%= @body_class -%>">
  <div id="jqt">
    <div>
      <div class="toolbar" id="top_nav">
        <%= render :partial => 'layouts/header' %>  
      </div>

      <div class="content_wrap clearfix">
        <%= yield %>
      </div>

      <div id="page_footer">
        <%= render :partial => 'layouts/footer' %>  
      </div>
    </div>
  </div>
</body>
</html>